name: Deploy Next.js Portfolio to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install --legacy-peer-deps
          npm install --save --legacy-peer-deps lucide-react@latest
          npm install --save --legacy-peer-deps framer-motion@latest
          npm install sharp

      - name: Create env file
        run: |
          touch .env
          echo "NEXT_PUBLIC_BASE_PATH=${{ github.event.repository.name }}" >> .env

      - name: Build with Next.js
        run: |
          npm run build
        env:
          CI: false

      - name: Copy public assets
        run: |
          mkdir -p out
          cp -r public/* out/ || true
          
      - name: Fix permissions
        run: |
          chmod -c -R +rX "out/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
